version = 0.1

[default.deploy.parameters]
stack_name = "git-url-shortener"
resolve_s3 = true
s3_prefix = "git-url-shortener"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
